# Application Name
spring.application.name=FoodieHub


# Server Port
server.port=${PORT:8080}


# ===============================
# Database Configuration
# ===============================

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}

# Default Admin Credentials
admin.default.username=${ADMIN_USERNAME}
admin.default.password=${ADMIN_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Connection Pool Settings for Free Cloud DB
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=40000
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.leak-detection-threshold=60000



# ===============================
# JPA / Hibernate Configuration
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.open-in-view=false

# ===============================
# File Upload (Food Image Upload)
# ===============================
foodiehub.upload.dir=C:/Users/DELL/spring-workspace/FoodieHub/src/main/webapp/images

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB

# ===============================
# Mail Configuration
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# Payment Gateway
# ===============================
razorpay.api.key=${RAZORPAY_API_KEY}

# ===============================
# MVC View Resolver (JSP)
# ===============================
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Prevent DevTools from restarting server on image upload
spring.devtools.restart.exclude=src/main/webapp/images/**
